### ISSUE TITLE
I want to create a ReactJS web but I don't know where to start

### ISSUE THREAD

**Issue by kij4040** [kij4040/first_proj#1]

**Comment by prince0010** [comment]
open your terminal and input this
npm create vite@latest 
and just input those needed you need to input
just pick the React and Vanilla Javascript
and then 'npm install' 'cd //directory' and then 'npm run dev'

**Comment by kij4040** [comment]
> open your terminal and input this npm create vite@latest and just input those needed you need to input just pick the React and Vanilla Javascript and then 'npm install' 'cd //directory' and then 'npm run dev'

Okay, I'll try this!
